/* construct the Hamiltonian matrix from the basis vectors */
// This constructs the Hamiltonian in a chosen winding number basis
#include<stdio.h>
#include<stdlib.h>
#include<iostream>
#include<fstream>
#include<math.h>
#include<vector>
#include<algorithm>
#include<iterator>
#include "define.h"

void constH(int sector){
   // workspace variables to construct the Hamiltonian  
   int i,j,k,p,q;
   int p1,p2,p3,p4;
   int n_Flip;
   int stateq,curr_index;
   bool pxy,pyz,pzw,pwx;
   std::vector<bool> newstate(2*VOL);
   std::vector<int> rowscan(VOL+1);
   // rowscan stores the elements of the cartoon states generated by the action of the Hamiltonian
   // the maximal number of NEW states that can be generated by action of the Hamiltonian on the
   // basis state = VOL. In addition, the lambda counts the number of flippable terms in the state.
   
   extern void eigcheck(std::vector<double>&, std::vector<std::vector<double>>&,int); 
   extern void diag_matrix(std::vector<MKL_INT>&,std::vector<MKL_INT>&,std::vector<double>&, 
    std::vector<double>&, std::vector<std::vector<double>>&,int);
   extern void printmatrix(std::vector<MKL_INT>&,std::vector<MKL_INT>&,std::vector<double>&);

   printf("Construct Hamiltonian in sector %d with basis states =%ld. \n",sector,Wind[sector].nBasis);
   curr_index=1;
   Wind[sector].rows.push_back(curr_index);
   // scan through the basis vectors in this sector
   for(i=0;i<Wind[sector].nBasis;i++){
      newstate = Wind[sector].basisVec[i];
      /* act on the basis state with the Hamiltonian */
      /* a single plaquette is arranged as 
                pzw
             o-------o
             |       |
        pwx  |   p   |  pyz
             |       |
             o-------o
                pxy
      */
      for(j=0;j<=VOL;j++) rowscan[j]=NTOT;
      stateq = 0;
      for(p=0;p<VOL;p++){
       // Find if a single plaquette is flippable 
       p1=2*p; p2=2*next[DIM+1][p]+1; p3=2*next[DIM+2][p]; p4=2*p+1;
       pxy=newstate[p1]; pyz=newstate[p2]; pzw=newstate[p3]; pwx=newstate[p4];
       if((pxy==pyz)&&(pzw==pwx)&&(pwx!=pxy)){
         // If flippable, act with the Hamiltonian 
         newstate[p1]=!newstate[p1]; newstate[p2]=!newstate[p2];
         newstate[p3]=!newstate[p3]; newstate[p4]=!newstate[p4];
         //check which state it is by scanning other states in the same sector
         // use the bin search if the basis states are sorted; it is much faster
         //q=Wind[sector].scan(newstate);
         q=Wind[sector].binscan(newstate);
         // store the position matrix element (i,stateq) 
         rowscan[stateq]=q; stateq++;
         //flip back the plq
         newstate[p1]=!newstate[p1]; newstate[p2]=!newstate[p2];
         newstate[p3]=!newstate[p3]; newstate[p4]=!newstate[p4];
         //if(newstate!=basis_flip[i]) std::cout<<"state mismatch"<<std::endl;
       }
     }
     //store the diagonal location
     rowscan[stateq]=i; stateq++;
     // get the #-of-flippable plaquettes of the basis state-i
     n_Flip=Wind[sector].nflip[i];
     // check
     if(stateq > (VOL+1)){ printf("Error in bound.\n"); }
     // sort the matrix columns
     std::sort (rowscan.begin(), rowscan.end()); 
     // construct the matrix in CSC format
     curr_index = curr_index + stateq;
     Wind[sector].rows.push_back(curr_index);
     for(k=0;k<stateq;k++){
       Wind[sector].cols.push_back(rowscan[k]+1);
       if(rowscan[k]==i) Wind[sector].hamil.push_back(lam*n_Flip);
       else Wind[sector].hamil.push_back(-1.0);
     }
   }
   // print the matrix for debugging
   //printf("size of rows = %d \n",(int)Wind[sector].rows.size());
   //for(k=0;k<Wind[sector].rows.size();k++) printf("row[%d] = %d \n",k,Wind[sector].rows[k]);
   //printf("size of cols = %d \n",(int)Wind[sector].cols.size());
   //for(k=0;k<Wind[sector].cols.size();k++) printf("col[%d] = %d \n",k,Wind[sector].cols[k]);
}

int WindNo::scan(std::vector<bool> &newstate){
     unsigned int m;
     // method 1 of searching using built-in c++ functions 
     // this is a bit faster (a few percent) than method 2
     std::vector<std::vector<bool>>::iterator it; 
     it = std::find(basisVec.begin(),basisVec.end(),newstate);
     if(it == basisVec.end()){
       std::cout<<"Element not found here! "<<std::endl; 
       return -100;
     }
     m  = std::distance(basisVec.begin(),it);
     return m;
     // method 2 of searching using a simple comparison. 
     /* 
     for(int m=0;m<nBasis;m++){
       if(newstate==basisVec[m]) return m;
     }
     return -100; */
 }

void printmatrix(std::vector<MKL_INT> &rows, std::vector<MKL_INT> &cols, std::vector<double> &val){
 std::ofstream Outfile;
 int nrows, ncols;
 nrows = rows.size(); ncols = cols.size();
 Outfile.open("sparse_mat.bin",std::ios::out);
 Outfile.write((char*)&nrows, sizeof(int));
 Outfile.write((char*)&ncols, sizeof(int));
 Outfile.write((char*)&rows[0], rows.size()*sizeof(MKL_INT));
 Outfile.write((char*)&cols[0], cols.size()*sizeof(MKL_INT));
 Outfile.close();
} 
